openapi: 3.1.0
info:
  version: 1.0.0
  title: Codewars API
  contact:
    url: https://github.com/noid-dev/codewars-openapi
  license:
    name: MIT
    url: https://github.com/noid-dev/codewars-openapi/blob/main/LICENSE
  description: >
    Codewars API documentation - [https://dev.codewars.com](https://dev.codewars.com)
servers:
  - url: https://www.codewars.com
security: [ ]
paths:
  /api/v1/users/{user}:
    $ref: ./paths/Users.yaml
  /api/v1/users/{user}/code-challenges/completed:
    $ref: ./paths/CompletedChallenges.yaml
  /api/v1/users/{user}/code-challenges/authored:
    $ref: ./paths/AuthoredChallenges.yaml
  /api/v1/code-challenges/{challenge}:
    $ref: ./paths/Challenges.yaml