name: Build Codewars OAS

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Setup Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Bundle definitions
        run: npm run build

#      - name: Publish summary
#        run: npm run stats >> $GITHUB_STEP_SUMMARY 2>&1

      - name: Validate definitions
        run: npm test

      - name: Upload OAS
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: codewars-openapi
          path: ./public/codewars.yaml