name: Build Codewars OAS

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Setup Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 18

      - name: Bundle OpenAPI definitions
        run: npx @redocly/cli@1.0.0-beta.118 bundle openapi/openapi.yaml --output=codewars.yaml

      - name: Upload OAS
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: codewars-openapi
          path: codewars.yaml

  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download OAS
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7

      - name: Lint OpenAPI definitions
        run: npx @redocly/cli@1.0.0-beta.118 lint codewars.yaml >> $GITHUB_STEP_SUMMARY 2>&1