name: Build Codewars OAS

on:
  push:
    branches:
      - wip

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Setup Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Bundle definitions
        run: npm run build >> $GITHUB_STEP_SUMMARY 2>&1

      - name: Validate definitions
        run: npm test

      - name: Upload gh-pages artifacts
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: gh-pages
          path: ./public/

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          ref: gh-pages

      - name: Download gh-pages artifacts
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
        with:
          name: gh-pages

      - name: Update Git pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: sync-up triggered by run #$GITHUB_RUN_NUMBER" -m "SHA: $GITHUB_SHA"
            git push -f origin gh-pages
            echo '☑️ GitHub Pages have been updated.' >> $GITHUB_STEP_SUMMARY
          else
            echo '✅ GitHub Pages are already up-to-date.' >> $GITHUB_STEP_SUMMARY
          fi